# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detlay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 327)
        MainWindow.setStyleSheet("background-color:rgb(116, 116, 116);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 70, 81, 51))
        self.label.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 14pt \"Nirmala UI\";\n"
"background:transparent;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 70, 81, 51))
        self.label_2.setStyleSheet("color:rgb(63, 255, 5);\n"
"font: 75 16pt \"Nirmala UI\";\n"
"background:transparent;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 20, 221, 51))
        self.label_3.setStyleSheet("color:black;\n"
"font: 75 14pt \"Nirmala UI\";\n"
"background:transparent;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 151, 51))
        self.label_4.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 14pt \"Nirmala UI\";\n"
"background:transparent;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 120, 721, 51))
        self.label_5.setStyleSheet("color:rgb(63, 255, 5);\n"
"font: 75 16pt \"Nirmala UI\";\n"
"background:transparent;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 170, 81, 51))
        self.label_6.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 14pt \"Nirmala UI\";\n"
"background:transparent;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 220, 101, 51))
        self.label_7.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 75 14pt \"Nirmala UI\";\n"
"background:transparent;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 170, 851, 51))
        self.label_8.setStyleSheet("color:rgb(63, 255, 5);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"background:transparent;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(160, 220, 81, 51))
        self.label_9.setStyleSheet("color:rgb(63, 255, 5);\n"
"font: 75 16pt \"Nirmala UI\";\n"
"background:transparent;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cpu Per :"))
        self.label_3.setText(_translate("MainWindow", "Current cpu performance"))
        self.label_4.setText(_translate("MainWindow", "Cpu Frequency :"))
        self.label_6.setText(_translate("MainWindow", "Cpu Stats:"))
        self.label_7.setText(_translate("MainWindow", "Cpu Count:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
